name: Publish Docker image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dlrobson
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            UID=1000
            GID=1000
          push: ${{ github.event_name != 'pull_request' }}
          tags: dlrobson/latex-dev-container:latest
          platforms: linux/amd64,linux/arm64
