name: Publish Docker image

on:
  push:
    branches:
      - main
  pull_request:

# This stops any running jobs when a new commit is pushed
# Reference: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  version_info:
    name: Generate Version Info
    runs-on: ubuntu-latest
    outputs:
      software_version: ${{ steps.version_info.outputs.software_version }}
    steps:
      # We will use the date and month as the tag for the image in the format YYYY-MM.
      # This will allow us to store older images and easily identify when they were built.
      # I don't need finer granularity than this for my use case. This will be set in the
      # version_info job and used in the build_image jobs
      - id: version_info
        run: echo "software_version=$(date +%Y-%m)" >> $GITHUB_OUTPUT

  build_image:
    name: Build and Publish Images
    needs: version_info
    uses: dlrobson/dotfiles/.github/workflows/build_image_reusable.yml@master
    with:
      base-image: ubuntu:latest
      image-name: latex-dev-container
      software-version: ${{ needs.version_info.outputs.software_version }}
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
